/* ============================================================
   EXERCISE DATABASE
   met = metabolic equivalent, used for calorie estimation
   type: 'strength' (sets x reps x weight) | 'cardio' (duration based) | 'bodyweight'
   ============================================================ */
const EXERCISE_DB = [
  // ---- CHEST ----
   
{"id":"bench-press-barbell","name":"Barbell Bench Press","muscle":"chest","icon":"🏋️","type":"strength","met":5.0,"videoUrl":"https://www.youtube.com/watch?v=gRVjAtPip0Y","bodyMap":["chest","triceps","shoulders"]}, {"id":"bench-press-dumbbell","name":"Dumbbell Bench Press","muscle":"chest","icon":"🏋️","type":"strength","met":5.0,"bodyMap":["chest","triceps","shoulders"],"videoUrl":"https://www.youtube.com/watch?v=J-gWN5hYwRU"}, {"id":"incline-bench-press","name":"Incline Bench Press","muscle":"chest","icon":"🏋️","type":"strength","met":5.0,"bodyMap":["chest","shoulders","triceps"],"videoUrl":"https://www.youtube.com/watch?v=SrqOu55lrYU"}, {"id":"decline-bench-press","name":"Decline Bench Press","muscle":"chest","icon":"🏋️","type":"strength","met":5.0,"videoUrl":"https://www.youtube.com/results?search_query=decline+bench+press+proper+form","bodyMap":["chest","triceps"]}, {"id":"chest-fly-dumbbell","name":"Dumbbell Chest Fly","muscle":"chest","icon":"🏋️","type":"strength","met":4.5,"videoUrl":"https://www.youtube.com/results?search_query=dumbbell+chest+fly+proper+form","bodyMap":["chest"]}, {"id":"cable-crossover","name":"Cable Crossover","muscle":"chest","icon":"🏋️","type":"strength","met":4.5,"videoUrl":"https://www.youtube.com/watch?v=OfSpPLXaEDk","bodyMap":["chest"]}, {"id":"push-up","name":"Push-Up","muscle":"chest","icon":"💪","type":"bodyweight","met":3.8,"bodyMap":["chest","triceps","shoulders"],"videoUrl":"https://www.youtube.com/results?search_query=push+up+proper+form"}, {"id":"dips-chest","name":"Chest Dips","muscle":"chest","icon":"💪","type":"bodyweight","met":5.5,"bodyMap":["chest","triceps"],"videoUrl":"https://www.youtube.com/results?search_query=chest+dips+proper+form"}, {"id":"dips-assisted","name":"Assisted Dips","muscle":"chest","icon":"💪","type":"strength","met":4.5,"assisted":true,"videoUrl":"https://www.youtube.com/watch?v=P9CkuhCc0TE","bodyMap":["chest","triceps"]}, {"id":"pec-deck","name":"Pec Deck Machine","muscle":"chest","icon":"🏋️","type":"strength","met":4.0,"bodyMap":["chest"],"videoUrl":"https://www.youtube.com/watch?v=ybi3NPUK47M"}, {"id":"chest-press-machine","name":"Chest Press Machine","muscle":"chest","icon":"🏋️","type":"strength","met":4.5,"videoUrl":"https://www.youtube.com/watch?v=pLofEAcfsO8","bodyMap":["chest","triceps","shoulders"]},

{"id":"deadlift","name":"Deadlift","muscle":"back","icon":"🏋️","type":"strength","met":6.0,"videoUrl":"https://www.youtube.com/watch?v=p2OPUi4xGrM","bodyMap":["lower_back","glutes","hamstrings","lats","upper_back"]}, {"id":"pull-up","name":"Pull-Up","muscle":"back","icon":"💪","type":"bodyweight","met":8.0,"bodyMap":["lats","biceps"],"videoUrl":"https://www.youtube.com/watch?v=TMnxKjdYcME"}, {"id":"chin-up","name":"Chin-Up","muscle":"back","icon":"💪","type":"bodyweight","met":8.0,"bodyMap":["lats","biceps"],"videoUrl":"https://www.youtube.com/watch?v=liebDvbcdow"}, {"id":"pull-up-assisted","name":"Assisted Pull-Up","muscle":"back","icon":"💪","type":"strength","met":5.5,"assisted":true,"videoUrl":"https://www.youtube.com/watch?v=wFj808u2HWU","bodyMap":["lats","biceps"]}, {"id":"lat-pulldown","name":"Lat Pulldown","muscle":"back","icon":"🏋️","type":"strength","met":5.0,"videoUrl":"https://www.youtube.com/watch?v=Z_3xHwuO8Tk","bodyMap":["lats","biceps"]}, {"id":"barbell-row","name":"Barbell Row","muscle":"back","icon":"🏋️","type":"strength","met":5.5,"videoUrl":"https://www.youtube.com/watch?v=ML1L5ytxLMY","bodyMap":["lats","upper_back","biceps"]}, {"id":"dumbbell-row","name":"Single-Arm Dumbbell Row","muscle":"back","icon":"🏋️","type":"strength","met":5.5,"bodyMap":["lats","upper_back","biceps"],"videoUrl":"https://www.youtube.com/results?search_query=single+arm+dumbbell+row+proper+form"}, {"id":"seated-cable-row","name":"Seated Cable Row","muscle":"back","icon":"🏋️","type":"strength","met":5.0,"videoUrl":"https://www.youtube.com/watch?v=f_r95UajQcg","bodyMap":["upper_back","lats","biceps"]}, {"id":"mid-row","name":"Mid Row","muscle":"back","icon":"🏋️","type":"strength","met":5.0,"bodyMap":["upper_back","lats"],"videoUrl":"https://www.youtube.com/results?search_query=mid+row+machine+proper+form"}, {"id":"t-bar-row","name":"T-Bar Row","muscle":"back","icon":"🏋️","type":"strength","met":5.5,"bodyMap":["upper_back","lats","biceps"],"videoUrl":"https://www.youtube.com/results?search_query=t+bar+row+proper+form"}, {"id":"face-pull","name":"Face Pull","muscle":"back","icon":"🏋️","type":"strength","met":3.5,"bodyMap":["upper_back","shoulders"],"videoUrl":"https://www.youtube.com/results?search_query=face+pull+proper+form"}, {"id":"hyperextension","name":"Back Extension","muscle":"back","icon":"💪","type":"bodyweight","met":4.0,"bodyMap":["lower_back","glutes"],"videoUrl":"https://www.youtube.com/results?search_query=back+extension+hyperextension+proper+form"}, {"id":"good-morning","name":"Good Morning","muscle":"back","icon":"🏋️","type":"strength","met":5.0,"bodyMap":["lower_back","hamstrings","glutes"],"videoUrl":"https://www.youtube.com/results?search_query=good+morning+exercise+proper+form"}, {"id":"shrugs","name":"Barbell Shrugs","muscle":"back","icon":"🏋️","type":"strength","met":3.5,"bodyMap":["upper_back"],"videoUrl":"https://www.youtube.com/watch?v=NAqCVe2mwzM"},

{"id":"squat-barbell","name":"Barbell Back Squat","muscle":"legs","icon":"🦵","type":"strength","met":6.0,"videoUrl":"https://www.youtube.com/watch?v=8PMjqgR8Wa8","bodyMap":["quads","glutes","hamstrings"]}, {"id":"front-squat","name":"Front Squat","muscle":"legs","icon":"🦵","type":"strength","met":6.0,"bodyMap":["quads","glutes"],"videoUrl":"https://www.youtube.com/results?search_query=front+squat+proper+form"}, {"id":"leg-press","name":"Leg Press","muscle":"legs","icon":"🦵","type":"strength","met":5.0,"videoUrl":"https://www.youtube.com/watch?v=ETOAyWM6i6A","bodyMap":["quads","glutes","hamstrings"]}, {"id":"lunges","name":"Walking Lunges","muscle":"legs","icon":"🦵","type":"bodyweight","met":5.0,"bodyMap":["quads","glutes","hamstrings"],"videoUrl":"https://www.youtube.com/results?search_query=walking+lunges+proper+form"}, {"id":"bulgarian-split-squat","name":"Bulgarian Split Squat","muscle":"legs","icon":"🦵","type":"strength","met":5.5,"bodyMap":["quads","glutes","hamstrings"],"videoUrl":"https://www.youtube.com/watch?v=hbw7hdyOpq0"}, {"id":"leg-extension","name":"Leg Extension","muscle":"legs","icon":"🦵","type":"strength","met":4.0,"bodyMap":["quads"],"videoUrl":"https://www.youtube.com/watch?v=tTbJBUKnWU8"}, {"id":"leg-curl","name":"Leg Curl","muscle":"legs","icon":"🦵","type":"strength","met":4.0,"bodyMap":["hamstrings"],"videoUrl":"https://www.youtube.com/watch?v=hqI59xXChFk"}, {"id":"romanian-deadlift","name":"Romanian Deadlift","muscle":"legs","icon":"🦵","type":"strength","met":5.5,"bodyMap":["hamstrings","glutes","lower_back"],"videoUrl":"https://www.youtube.com/watch?v=3VXmecChYYM"}, {"id":"hip-thrust","name":"Barbell Hip Thrust","muscle":"legs","icon":"🦵","type":"strength","met":5.0,"bodyMap":["glutes","hamstrings"],"videoUrl":"https://www.youtube.com/watch?v=S_uZP4UH6J0"}, {"id":"calf-raise","name":"Standing Calf Raise","muscle":"legs","icon":"🦵","type":"strength","met":3.5,"bodyMap":["calves"],"videoUrl":"https://www.youtube.com/watch?v=K_jsGgztcGU"}, {"id":"seated-calf-raise","name":"Seated Calf Raise","muscle":"legs","icon":"🦵","type":"strength","met":3.5,"bodyMap":["calves"],"videoUrl":"https://www.youtube.com/results?search_query=seated+calf+raise+proper+form"}, {"id":"hack-squat","name":"Hack Squat","muscle":"legs","icon":"🦵","type":"strength","met":6.0,"bodyMap":["quads","glutes"],"videoUrl":"https://www.youtube.com/results?search_query=hack+squat+proper+form"}, {"id":"goblet-squat","name":"Goblet Squat","muscle":"legs","icon":"🦵","type":"strength","met":5.5,"bodyMap":["quads","glutes"],"videoUrl":"https://www.youtube.com/watch?v=7-LTkLLQqe0"}, {"id":"box-jump","name":"Box Jump","muscle":"legs","icon":"🦵","type":"bodyweight","met":8.0,"bodyMap":["quads","glutes","calves"],"videoUrl":"https://www.youtube.com/results?search_query=box+jump+proper+form"},

{"id":"overhead-press","name":"Overhead Press","muscle":"shoulders","icon":"🏋️","type":"strength","met":5.0,"videoUrl":"https://www.youtube.com/watch?v=ZXpdJOLNoWw","bodyMap":["shoulders","triceps"]}, {"id":"dumbbell-shoulder-press","name":"Dumbbell Shoulder Press","muscle":"shoulders","icon":"🏋️","type":"strength","met":5.0,"bodyMap":["shoulders","triceps"],"videoUrl":"https://www.youtube.com/results?search_query=dumbbell+shoulder+press+proper+form"}, {"id":"lateral-raise","name":"Lateral Raise","muscle":"shoulders","icon":"🏋️","type":"strength","met":3.5,"bodyMap":["shoulders"],"videoUrl":"https://www.youtube.com/watch?v=3VcKaXpzqRo"}, {"id":"front-raise","name":"Front Raise","muscle":"shoulders","icon":"🏋️","type":"strength","met":3.5,"bodyMap":["shoulders"],"videoUrl":"https://www.youtube.com/results?search_query=dumbbell+front+raise+proper+form"}, {"id":"rear-delt-fly","name":"Rear Delt Fly","muscle":"shoulders","icon":"🏋️","type":"strength","met":3.5,"bodyMap":["shoulders","upper_back"],"videoUrl":"https://www.youtube.com/watch?v=lPt0GqwaqEw"}, {"id":"arnold-press","name":"Arnold Press","muscle":"shoulders","icon":"🏋️","type":"strength","met":5.0,"bodyMap":["shoulders","triceps"],"videoUrl":"https://www.youtube.com/watch?v=3ml7BH7mNwQ"}, {"id":"upright-row","name":"Upright Row","muscle":"shoulders","icon":"🏋️","type":"strength","met":4.5,"bodyMap":["shoulders","upper_back"],"videoUrl":"https://www.youtube.com/results?search_query=upright+row+proper+form"}, {"id":"shoulder-press-machine","name":"Shoulder Press Machine","muscle":"shoulders","icon":"🏋️","type":"strength","met":4.5,"videoUrl":"https://www.youtube.com/watch?v=TnhIyp4kmO8","bodyMap":["shoulders","triceps"]},

{"id":"bicep-curl-barbell","name":"Barbell Bicep Curl","muscle":"arms","icon":"💪","type":"strength","met":3.5,"bodyMap":["biceps"],"videoUrl":"https://www.youtube.com/watch?v=pQfJR-sSIvA"}, {"id":"bicep-curl-dumbbell","name":"Dumbbell Bicep Curl","muscle":"arms","icon":"💪","type":"strength","met":3.5,"videoUrl":"https://www.youtube.com/watch?v=6DeLZ6cbgWQ","bodyMap":["biceps"]}, {"id":"hammer-curl","name":"Hammer Curl","muscle":"arms","icon":"💪","type":"strength","met":3.5,"bodyMap":["biceps","forearms"],"videoUrl":"https://www.youtube.com/watch?v=TwD-YGVP4Bk"}, {"id":"preacher-curl","name":"Preacher Curl","muscle":"arms","icon":"💪","type":"strength","met":3.5,"bodyMap":["biceps"],"videoUrl":"https://www.youtube.com/results?search_query=preacher+curl+proper+form"}, {"id":"tricep-pushdown","name":"Tricep Pushdown","muscle":"arms","icon":"💪","type":"strength","met":3.5,"videoUrl":"https://www.youtube.com/watch?v=LXkCrxn3caQ","bodyMap":["triceps"]}, {"id":"tricep-dip","name":"Tricep Dip","muscle":"arms","icon":"💪","type":"bodyweight","met":5.0,"bodyMap":["triceps","chest"],"videoUrl":"https://www.youtube.com/results?search_query=tricep+dips+proper+form"}, {"id":"skull-crusher","name":"Skull Crusher","muscle":"arms","icon":"💪","type":"strength","met":3.5,"bodyMap":["triceps"],"videoUrl":"https://www.youtube.com/watch?v=kOXVmFFTcio"}, {"id":"overhead-tricep-extension","name":"Overhead Tricep Extension","muscle":"arms","icon":"💪","type":"strength","met":3.5,"bodyMap":["triceps"],"videoUrl":"https://www.youtube.com/watch?v=qkZBtEHUjfw"}, {"id":"close-grip-bench","name":"Close-Grip Bench Press","muscle":"arms","icon":"🏋️","type":"strength","met":4.5,"bodyMap":["triceps","chest"],"videoUrl":"https://www.youtube.com/results?search_query=close+grip+bench+press+proper+form"}, {"id":"cable-curl","name":"Cable Bicep Curl","muscle":"arms","icon":"💪","type":"strength","met":3.5,"bodyMap":["biceps"],"videoUrl":"https://www.youtube.com/watch?v=xG57S0fgXAk"},

{"id":"plank","name":"Plank","muscle":"core","icon":"🧘","type":"bodyweight","met":3.5,"bodyMap":["abs"],"videoUrl":"https://www.youtube.com/results?search_query=plank+proper+form"}, {"id":"crunches","name":"Crunches","muscle":"core","icon":"🧘","type":"bodyweight","met":3.5,"bodyMap":["abs"],"videoUrl":"https://www.youtube.com/results?search_query=crunches+proper+form"}, {"id":"hanging-leg-raise","name":"Hanging Leg Raise","muscle":"core","icon":"🧘","type":"bodyweight","met":4.5,"bodyMap":["abs"],"videoUrl":"https://www.youtube.com/results?search_query=hanging+leg+raise+proper+form"}, {"id":"russian-twist","name":"Russian Twist","muscle":"core","icon":"🧘","type":"bodyweight","met":4.0,"bodyMap":["obliques","abs"],"videoUrl":"https://www.youtube.com/results?search_query=russian+twist+proper+form"}, {"id":"cable-woodchopper","name":"Cable Woodchopper","muscle":"core","icon":"🧘","type":"strength","met":4.0,"bodyMap":["obliques"],"videoUrl":"https://www.youtube.com/results?search_query=cable+woodchopper+proper+form"}, {"id":"ab-wheel","name":"Ab Wheel Rollout","muscle":"core","icon":"🧘","type":"bodyweight","met":4.5,"bodyMap":["abs"],"videoUrl":"https://www.youtube.com/results?search_query=ab+wheel+rollout+proper+form"}, {"id":"mountain-climbers","name":"Mountain Climbers","muscle":"core","icon":"🧘","type":"bodyweight","met":6.0,"bodyMap":["abs"],"videoUrl":"https://www.youtube.com/results?search_query=mountain+climbers+proper+form"}, {"id":"side-plank","name":"Side Plank","muscle":"core","icon":"🧘","type":"bodyweight","met":3.5,"bodyMap":["obliques"],"videoUrl":"https://www.youtube.com/results?search_query=side+plank+proper+form"},

{"id":"incline-walk","name":"Incline Treadmill Walk","muscle":"cardio","icon":"🚶","type":"cardio","met":0,"special":"incline_walk","bodyMap":[],"videoUrl":"https://www.youtube.com/results?search_query=incline+treadmill+walking+proper+form"}, {"id":"treadmill-run","name":"Treadmill Run","muscle":"cardio","icon":"🏃","type":"cardio","met":9.8,"bodyMap":["quads","calves"],"videoUrl":"https://www.youtube.com/results?search_query=treadmill+running+proper+form"}, {"id":"stationary-bike","name":"Stationary Bike","muscle":"cardio","icon":"🚴","type":"cardio","met":7.0,"bodyMap":["quads"],"videoUrl":"https://www.youtube.com/results?search_query=stationary+bike+proper+form"}, {"id":"rowing-machine","name":"Rowing Machine","muscle":"cardio","icon":"🚣","type":"cardio","met":7.0,"bodyMap":["lats","biceps","quads","upper_back"],"videoUrl":"https://www.youtube.com/results?search_query=rowing+machine+proper+form"}, {"id":"elliptical","name":"Elliptical Trainer","muscle":"cardio","icon":"🏃","type":"cardio","met":5.0,"bodyMap":["quads","glutes"],"videoUrl":"https://www.youtube.com/results?search_query=elliptical+trainer+proper+form"}, {"id":"stairmaster","name":"StairMaster","muscle":"cardio","icon":"🪜","type":"cardio","met":8.8,"bodyMap":["quads","glutes","calves"],"videoUrl":"https://www.youtube.com/results?search_query=stairmaster+proper+form"}, {"id":"jump-rope","name":"Jump Rope","muscle":"cardio","icon":"🪢","type":"cardio","met":11.0,"bodyMap":["calves"],"videoUrl":"https://www.youtube.com/results?search_query=jump+rope+proper+form"}, {"id":"swimming","name":"Swimming (freestyle)","muscle":"cardio","icon":"🏊","type":"cardio","met":8.0,"bodyMap":["lats","shoulders"],"videoUrl":"https://www.youtube.com/results?search_query=freestyle+swimming+proper+technique"}, {"id":"cycling-outdoor","name":"Outdoor Cycling","muscle":"cardio","icon":"🚴","type":"cardio","met":8.0,"bodyMap":["quads"],"videoUrl":"https://www.youtube.com/results?search_query=outdoor+cycling+proper+technique"}, {"id":"flat-walk","name":"Flat Walk","muscle":"cardio","icon":"🚶","type":"cardio","met":3.5,"bodyMap":[],"videoUrl":"https://www.youtube.com/results?search_query=walking+exercise+proper+form"},

{"id":"clean-and-jerk","name":"Clean and Jerk","muscle":"fullbody","icon":"🏋️","type":"strength","met":7.0,"bodyMap":["quads","glutes","shoulders","upper_back"],"videoUrl":"https://www.youtube.com/results?search_query=clean+and+jerk+proper+form"}, {"id":"snatch","name":"Snatch","muscle":"fullbody","icon":"🏋️","type":"strength","met":7.0,"bodyMap":["quads","glutes","shoulders","upper_back"],"videoUrl":"https://www.youtube.com/results?search_query=barbell+snatch+proper+form"}, {"id":"kettlebell-swing","name":"Kettlebell Swing","muscle":"fullbody","icon":"🏋️","type":"strength","met":6.5,"bodyMap":["glutes","hamstrings","lower_back"],"videoUrl":"https://www.youtube.com/results?search_query=kettlebell+swing+proper+form"}, {"id":"farmers-walk","name":"Farmer's Walk","muscle":"fullbody","icon":"🏋️","type":"strength","met":5.5,"bodyMap":["forearms","upper_back"],"videoUrl":"https://www.youtube.com/results?search_query=farmer+walk+proper+form"}, {"id":"burpees","name":"Burpees","muscle":"fullbody","icon":"💪","type":"bodyweight","met":8.0,"bodyMap":["chest","quads","shoulders"],"videoUrl":"https://www.youtube.com/results?search_query=burpees+proper+form"}, {"id":"thruster","name":"Thruster","muscle":"fullbody","icon":"🏋️","type":"strength","met":7.0,"bodyMap":["quads","glutes","shoulders"],"videoUrl":"https://www.youtube.com/results?search_query=barbell+thruster+proper+form"}, {"id":"battle-ropes","name":"Battle Ropes","muscle":"fullbody","icon":"🏋️","type":"cardio","met":7.5,"bodyMap":["shoulders","forearms"],"videoUrl":"https://www.youtube.com/results?search_query=battle+ropes+proper+form"} ]

const MUSCLE_GROUPS = [
  {id:'all', label:'All'},
  {id:'chest', label:'Chest'},
  {id:'back', label:'Back'},
  {id:'legs', label:'Legs'},
  {id:'shoulders', label:'Shoulders'},
  {id:'arms', label:'Arms'},
  {id:'core', label:'Core'},
  {id:'cardio', label:'Cardio'},
  {id:'fullbody', label:'Full Body'},
];
